FROM ruby:3.1

RUN gem install bundler
RUN apt-get update && apt-get install iputils-ping=3:20210202-1 -y

WORKDIR /usr/src/app

COPY Gemfile ./
RUN bundle config set --local without api && bundle install
