version: '3'
services:
  api:
    image: erikap/ruby-sinatra
    ports:
      - "3000:80"
    volumes:
      - ".:/usr/src/app"
    env_file:
      - ./.env
    stdin_open: true

  ping:
    build:
      context: .
      dockerfile: ./Dockerfile_ping
    command: ruby -e "require_relative 'ping'; Ping.new"
    depends_on:
      - "db"
    volumes:
      - .:/usr/src/app
    env_file:
      - ./.env

  db:
    image: postgres:11-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
        - ./.env

volumes:
  postgres: